#!/bin/sh

LUA=lua
CC=gcc
#CFLAGS=-g
CFLAGS="-O2 -Wall"
LFLAGS="-llua"

LUAFILE=$1
FILENAME=${LUAFILE%.*}
CFILE=${FILENAME}.c

${LUA} lua2c.lua ${LUAFILE} > ${CFILE} || exit 1
${CC} ${CFLAGS} ${CFILE} -o ${FILENAME} ${LFLAGS} || exit 1
shift
./${FILENAME} $@
